spring.application.name=SaC

player.total_positions=10
classic.points=16

logging.level.org.springframework.web.socket=info
logging.file.name=tmp/logs/sac.log
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss} %highlight(%-5level) --- [%15.15t] %clr([roomId=%X{roomId}]){green} %clr(%logger{40}){cyan} - %msg%n

server.port=80

management.otlp.metrics.export.enabled=false